version: "3.8"
services:
  redis:
    container_name: newmax-redis
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - redis
    restart: unless-stopped
    volumes:
      - redis_volume_data:/data
      - redis_insight_volume_data:/db
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  redis_volume_data:
  redis_insight_volume_data:

networks:
  redis:
    name: redis-network
    driver: bridge
